data_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/isic-2024-challenge
image_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/isic-2024-challenge/train-image/image
train_df_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/isic-2024-challenge/train-metadata-gkffold.csv
local_dir: /content/drive/MyDrive/24_7_ISIC2024/Output
pretrain_dir: 
COLAB: False
test: True
expname: EffNet0b_GKF
ver: 
sampling_rate: 0.5

model_name: tf_efficientnet_b0.ns_jft_in1k
num_classes: 2
dropout: 0.1
aux_loss_ratio:
gem_p: 3

batch_size: 64
epochs: 10
lr: 1e-4
early_stopping_rounds: 3
num_splits: 5
do_mixup: True

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

img_size: 256
remove_hair_thresh: 10
gkf: True