data_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/all-isic-data-20240629
data_dir_archive: /content/drive/MyDrive/24_7_ISIC2024/Input/all-isic-data-gkf-256
image_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/all-isic-data-20240629/train-image/image
train_df_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/all-isic-data-20240629/archive_train_gkf.csv
local_dir: /content/drive/MyDrive/24_7_ISIC2024/Output
pretrain_dir:
COLAB: False
test: True
expname: EffNet0b_Pretraining
ver: 1
sampling_rate: 0.5
weighted_loss: True

model_name: tf_efficientnet_b0.ns_jft_in1k
num_classes: 2
aux_loss_ratio:
gem_p: 3
drop_path_rate: 0.1
dropout: 0.1

batch_size: 64
epochs: 10
lr: 5e-4
early_stopping_rounds: 3
num_splits: 5
do_mixup: True

device: cuda:0
num_workers: 4
seed: 42
use_wandb: False

img_size: 256
remove_hair_thresh: 10