data_dir: /kaggle/input/isic-2024-challenge
image_dir: /kaggle/input/isic-2024-challenge/train-image/image
train_df_dir:
local_dir: 
pretrain_dir:
COLAB: False
test: True
expname: 
ver: 

model_name: tf_efficientnet_b0.ns_jft_in1k
num_classes: 2
dropout: 0.1
aux_loss_ratio: None

batch_size: 32
epochs: 20
lr: 1e-3 #1e-4
early_stopping_rounds: 3
num_splits: 5
do_mixup: 0.5

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

img_size: 256
remove_hair_thresh: 10
gkf: False