data_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/isic-2024-challenge
image_dir: /content/drive/MyDrive/24_7_ISIC2024/Input/isic-2024-challenge/train-image/image
train_df_dir: /content/drive/MyDrive/24_7_ISIC2024/Output
local_dir: 
pretrain_dir:
COLAB: False
test: True
expname: EffNet0b_Pretraining
ver: 1
sampling_test:False

model_name: tf_efficientnet_b0.ns_jft_in1k
num_classes: 2
dropout: 0.1
aux_loss_ratio:

batch_size: 32
epochs: 10
lr: 5e-4
early_stopping_rounds: 3
num_splits: 5
do_mixup: True

device: cuda:0
num_workers: 4
seed: 1234
use_wandb: False

img_size: 256
remove_hair_thresh: 10
gkf: False